### ISSUE TITLE
Add a getDouble feature

### ISSUE THREAD

**Issue by GaryHilares** [GaryNLOL/GSS-Language#1]
## Description
Sometimes we need to manage data that contains floating points data. By now, a possible workaround would be to store an integer, use `getInt` to store it and then divide it by base 10 number, but this removes the simplicity of the requests and generates problems with numbers that have a variable number of decimal digits. This can be solved adding a `getDouble` feature and would maintain the style of the library.

## Example
properties.gss
```gss
RPG =
   Hero =
      life: 42.5;
      attack: 38.0:
   end
end
```

main.cpp
```cpp
#include <GSS/Reader.hpp>
#include <iostream>
#include <cmath>

int main()
{
   GSS::PropertySheet rpgData = GSS::PropertySheet::loadFromFile("properties.gss");
   double life = rpgData.getDouble("RPG::hero::life");
   double attack = rpgData.getDouble("RPG::hero::attack");
   std::cout << life << std::endl; // Outputs 42,5.
   std::cout << ceil(life) << std::endl; // Outputs 43,0.
}
```

**Comment by misterblack0101** [comment]
Hey, I want to start contributing to open source, and searching for good first issues led me here. Could you please guide me on what I should do next?

**Comment by GaryHilares** [comment]
Sure. I suppose you have Git installed as well as some C++ knowledge and a text editor or IDE that is correctly configured for C++.

Contributing to an open source project may be difficult at the start, but once you get used to it you will think it is pretty simple. I see you have already have forked the repository. Now you just need to follow these steps:
1. In Git, use the following command replacing `${link of your fork}`:
```git
        git clone ${link of your fork}
```
- In this case, the link of your fork is `https://github.com/harshmaroo/GSS-Language.git`, so the command is:
```git
       git clone https://github.com/harshmaroo/GSS-Language.git
```
2. Now you have the repository locally in your PC. Open the header in your favorite text editor or IDE.
3. Write the function that is needed, in this case `getDouble`. The implementation is probably similar to the implementation of the `getInt` function. You may find stod useful. [Its documentation is here](https://en.cppreference.com/w/cpp/string/basic_string/stof).
4. Test for your function. You may want to use the file I posted with the issue. If your function fails, you will have to correct your function until it is correct. Once it passes all tests, continue with the step 5.
5. Save the changes.
6. Go to Git and stage your changes:
```git
        git add ${relative path of the file to stage}
```
- In this case you will have to replace `${relative path of the file to stage}` with `git add include/GSS/Reader.hpp` (from the root folder):
```git
        git add include/GSS/Reader.hpp
```
7. Commit those changes:
```git
        git commit -m "{a message describing the changes}"
```
8. Push those changes with the following command:
```git
        git push
```
9. Go back to GitHub and create a Pull Request (PR):
![pull-request-button](https://user-images.githubusercontent.com/46727048/112324871-33a42f80-8c81-11eb-8388-933024607112.png)

That's it! I will review your Pull Request and if everything is OK your changes will become part of the main branch.

**Comment by misterblack0101** [comment]
- I did a pull request for correcting the path to Reader.hpp in test.hpp. Please let me know if I did it right, and/or any kind of improvements I should make while doing this kind of stuff (Still pretty new to GitHub and making actual projects, not just writing chunks of code).

>  std::cout << ceil(life) << std::endl; // Outputs 42,0.
- Also in the example that you gave above, shouldn't the ceil value of 42.5 be 43?

- I'm still trying to figure out the code and test.cpp. Also, I will have to create a main.cpp in there, since it's not there, right?

**P.S. Thanks for all your help and co-operation.**

**Comment by GaryHilares** [comment]
- Your pull request was very nice. You did it right.
- Yes, sorry for that, it should be 43,0. I will edit it.
- There is a main method is in `tests.cpp`. Itself, [`main.cpp` is not always required](https://stackoverflow.com/questions/8628426/is-main-cpp-required#:~:text=No%2C%20you%20don't%20need,would%20not%20require%20main().). In this case I did not created one because the project is a library that focuses on the headers, not on the sources and I use source files mainly for testing.

**Comment by misterblack0101** [comment]
Hey @GaryNLOL . I've added a fix for the issue,  which I think should work fine. Please let me know if there's any kind of improvements that I could've made. Thanks for your help.👍🏼

**Comment by GaryHilares** [comment]
Perfect, you correctly implemented the feature. Thanks! If you wish you can continue helping with other issues/proposing new features or enhancements.

**Comment by GaryHilares** [comment]
BTW I'm propably going to make a commit and you will have to update your fork. [Here](https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a) there is a simple step-by-step guide of how doing it. If you have problems with doing it let me know.

**Comment by misterblack0101** [comment]
> Perfect, you correctly implemented the feature. Thanks! If you wish you can continue helping with other issues/proposing new features or enhancements.

Hey, I tried the best I could, but I couldn't understand most of the code. Although, I loved the overall experience of learning, and I did learn a lot, and would love to help more with this. Is there any other way we can communicate directly?

**Comment by GaryHilares** [comment]
I guess we can use Discord. Send me  your user id.

**Comment by misterblack0101** [comment]
> I guess we can use Discord. Send me  your user id.

misterblack#4630

**Comment by GaryHilares** [comment]
I had trouble sending you an invitation so I have added an invitation to a server in `README.md`.

**Comment by GaryHilares** [comment]
@all-contributors please add @harshmaroo for code
